### PR TITLE
chore: add template files

### PR DESCRIPTION
**Pull request by JeremyWu917**
Add template files ☕

### CODE REVIEW

**Comment by JeremyWu917** [comment]
Hi there,
After merged this PR, it will be like below screenshots when people file a issues report.
Thanks.

**Comment by JeremyWu917** [comment]
@microsoft-github-policy-service agree

**Review by darrenge — APPROVED** [review]
This all sounds good. Maybe after using it a bit we will have adjustments but this is a good first step.

**Comment by irinasp** [comment]
It looks nice!
As a suggestion: I would add "OS" and "Release version" as required steps in bug_report.yml
And it would be nice to have more options for the dropdown "Feature request title" in feature_request.yml such as New Feature, Improvement to Existing feature, Performance Enhancement, Other.

**Review by badrishc — APPROVED** [review]

**Pull request merged**
