### PR TITLE
chore: skip nightly & locker workflows on forks

### PR DESCRIPTION
**Pull request by Meir017**
both the nightly & locker workflow depend on some configuration that is set only on the main garnet repo (not on forks)

### CODE REVIEW

**Comment by badrishc** [comment]
Why exactly do nightly runs fail on forks, what's the error? Can we fix that instead of disabling?

**Comment by Meir017** [comment]
getting many messages of `Environment variable RunAzureTests is not defined` (see https://github.com/Meir017/garnet/actions/runs/10643408367/job/29506930910)

looks like the job fails due to timing out.

**Comment by badrishc** [comment]
> getting many messages of `Environment variable RunAzureTests is not defined` (see https://github.com/Meir017/garnet/actions/runs/10643408367/job/29506930910)
> 
> looks like the job fails due to timing out.

@TedHartMS - Tsavorite tests failing here, any idea why?

**Review by darrenge — APPROVED** [review]
Agree, this would be good to skip on forks

**Comment by badrishc** [comment]
We decided that it would be better to run these actions even on forks so that any errors can be worked on by forking contributors. The nightly job is just a copy of https://github.com/dotnet/orleans/blob/main/.github/workflows/locker.yml where they do not disable it on forks either. Once you fork, you can always disable them on your fork as opt-in. Closing accordingly.

**Pull request closed without merging**
