### PR TITLE
Update NOTICE.md, README.md and SECURITY.md

### PR DESCRIPTION
**Pull request by skanda890**

### CODE REVIEW

**Comment by MartinJohns** [comment]
Duplicate of #279. Just re-creating the PR when it was earlier rejected is very very rude.

**Comment by skanda890** [comment]
I didn't know that

**Comment by skanda890** [comment]
But can you tell why that got rejected

**Comment by badrishc** [comment]
Most of these files are boilerplate provided by github/microsoft org and we cannot change them. Cache-store is what we are calling this class of systems, not "cache store". Very minor edits like commas do not merit a pull request either. Thanks.

**Pull request closed without merging**
