### PR TITLE
Refactor Tsavorite checkpoint path handling to be OS-aware

### PR DESCRIPTION
**Pull request by PaulusParssinen**

### CODE REVIEW

**Review by TedHartMS — APPROVED** [review]

**Comment by PaulusParssinen** [comment]
Something funny happening with the paths used in the cloud tests?

**Comment by PaulusParssinen** [comment]
The problem is the fact that Tsavorite previously assumed all path-seperators to be ``/`` and let the windows NT APIs to deal with this instead. This PR makes this OS-aware and uses ``\`` for Windows which made the Azure storage tests explode as they use the same naming scheme. I propose to introducing a seperate `ICheckpointNamingScheme` in the AzureStorageDevice for this.. I'll test how that'd work out.

**Comment by PaulusParssinen** [comment]
Making rest of the Tsavorite tests use `System.IO.Path` APIs for consistency.

**Comment by PaulusParssinen** [comment]
Actually, I'll have that in separate PR.

**Review by TedHartMS — APPROVED** [review]
Looks good

**Pull request merged**
