### PR TITLE
[Compatibility] Added CLIENT GETNAME, SETNAME, SETINFO commands

### PR DESCRIPTION
**Pull request by Vijay-Nirmal**
Adding the CLIENT GETNAME, SETNAME, SETINFO commands to garnet

- [x] Add CLIENT GETNAME, SETNAME, SETINFO commands
- [x] Add Integration Test cases, ACL Test
- [x] Add documentation

### CODE REVIEW

**Review by vazois — APPROVED** [review]
Nice work! Please resolve any conflicts

**Comment by vazois** [comment]
@Vijay-Nirmal please resolve the conflicts because we cannot merge it as is

**Comment by Vijay-Nirmal** [comment]
@vazois Done

**Comment by yuseok-kim-edushare** [comment]
Wow! Awesome!
Thank you for your works, this working improve compatibility,
ex in java) Spring data redis , lettuce

**Pull request merged**
