### PR TITLE
[Compatibility] Added SMISMEMBER command

### PR DESCRIPTION
**Pull request by Vijay-Nirmal**
Adding SMISMEMBER command to garnet

- [x] Add SMISMEMBER command
- [x] Add Integration Test cases, ACL Test and Slot Verification Test
- [x] Add documentation

### CODE REVIEW

**Comment by yrajas** [comment]
Thanks for your continued contributions!

Possible to add the ArgSlice variant of the API in GarnetAPIObjectCommands.cs for SetIsMember to enable programmatic access?

**Review by yrajas — CHANGES_REQUESTED** [review]
Programmatic access API to be added.

**Comment by Vijay-Nirmal** [comment]
@yrajas Should I add it without any reference(caller)? or should I create a new method in SetCommands.cs as well?

**Comment by yrajas** [comment]
> @yrajas Should I add it without any reference(caller)? or should I create a new method in SetCommands.cs as well?

Programmatic access happens using IGarnetAPI so caller in SetCommands.cs is not needed.
You can check implementations like 

public GarnetStatus SetMembers(ArgSlice key, out ArgSlice[] members) in GarnetApiObjectCommands.cs based on the interface declaration in IGarnetApi.cs 
This in turn needs an implementation in SetOps.cs like 
internal unsafe GarnetStatus SetMembers<TObjectContext>(ArgSlice key, out ArgSlice[] members, ref TObjectContext objectStoreContext)

Also, tests in TestProcedureSet.cs

**Comment by yrajas** [comment]
> @yrajas Done, Added Garnet Api and added a test in TestProcedureSet.cs

Thanks. Looks good.
Once the conflicts are resolved, this can be merged.

**Review by yrajas — APPROVED** [review]

**Pull request merged**
